baseURL: //affectionate-curran-75f601.netlify.com
languageCode: en-us
title: Shugofa’s Book Nook
author: Shugofa Danesh
copyright: Copyright © 2019 Shugofa Danesh
paginate: 5
theme: newsprint
metaDataFormat: yaml

# params:
#   subtitle: Cave ab homine unius libri
