---
label: Default
hide_body: false
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
- type: datetime
  name: date
  label: Date
  config:
    required: true
- type: file
  name: thumbnail
  label: Thumbnail
pages:
- content/posts/if-you-are-out-there.md
- content/posts/things-i-m-great-at-and-am-grateful-for.md
- content/posts/dealing-with-emotional-pain.md
- content/posts/becoming-more-involved-in-the-real-world.md
- content/posts/Letting Ourselves Heal with Art.md
- content/posts/hello-hello.md
- content/posts/30-days-of-yoga-challenge.md
