---
label: Default
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
- type: datetime
  name: date
  label: Date
  config:
    required: true
- type: file
  name: thumbnail
  label: Thumbnail
pages:
- content/posts/30-days-of-yoga-challenge.md
- content/posts/Letting Ourselves Heal with Art.md
- content/posts/hello-hello.md
- content/posts/becoming-more-involved-in-the-real-world.md
